name = input()
price = int(input())
weight = int(input())
money = int(input())

print("================Чек================")
print("Товар:" + " " * (29 - len(name)) + name)
print("Цена:" + " " * (19 - len(str(weight) + str(price))) + str(weight) + "кг * " + str(price) + "руб/кг")
print("Итого:" + " " * (26 - len(str(weight * price))) + str(weight * price) + "руб")
print("Внесено:" + " " * (24 - len(str(money))) + str(money) + "руб")
print("Сдача:" + " " * (26 - len(str(money - weight * price))) + str(money - weight * price) + "руб")
print("===================================")
